# generate volume lookup table.

print("""
; ----------------------------------------------------------------------------
; DO NOT MODIFY: generated by volgen.py
; ----------------------------------------------------------------------------

#include "tinysynth.inc"

; ----------------------------------------------------------------------------
; volume table (top nybble/row is volume, bottom nybble/column is sample)

.section .text$A
.global volume_table
.size volume_table, VOLUME_TABLE_SIZE
.type volume_table, @object
volume_table:""")

maxvol = [
	0x00, 0x11, 0x22, 0x33,
	0x44, 0x55, 0x66, 0x77,
	0x88, 0x99, 0xAA, 0xBB,
	0xCC, 0xDD, 0xEE, 0xFF]

def lerp(samp, max):
	return int(samp / 0xF * max)

for vol in range(0, 16):
	print("	.byte ", end='')
	for samp in range(0, 16):
		pro = lerp(samp, maxvol[vol])
		print("0x{:02X}{} ".format(pro, '' if samp == 15 else ','), end='')
	print()